---
- name: Test if repo {{ repo.name }} exists
  command: cobbler repo report --name={{ repo.name }}
  failed_when: false
  register: repo_exist

- name: add repo if not exists
  command: cobbler repo add --name={{ repo.name }} --arch={{ repo.arch }} --mirror={{ repo.mirror }}
  when: repo_exist.rc != 0