- name: Add systems to cobbler
  shell: cobbler system add --name={{ item.key }} 
         --profile={{ cobbler_distro_name }}-{{ cobbler_distro_arch }}
         --interface={{ item.value.nic }}
         --mac={{ item.value.mac }}
         --ip-address={{ item.value.ipaddr }}
         --netmask={{ item.value.netmask }}
         --static=1 
         --hostname={{ item.key }}
         --dns-name={{ item.key }}
  with_dict: "{{ nodes }}"
  tags:
    - addnode
    
- name: Cobbler Sync
  shell: cobbler sync
  tags:
    - addnode
